// Code generated by golex. DO NOT EDIT.

package parser

import (
	"strconv"

	"modernc.org/golex/lex"
)

func (l *lexer) scan(lval *yySymType) lex.Char {
	c := l.Enter()

yystate0:
	yyrule := -1
	_ = yyrule
	c = l.Rule0()

	goto yystart1

	goto yystate0 // silence unused label error
	goto yyAction // silence unused label error
yyAction:
	switch yyrule {
	case 1:
		goto yyrule1
	case 2:
		goto yyrule2
	case 3:
		goto yyrule3
	case 4:
		goto yyrule4
	case 5:
		goto yyrule5
	case 6:
		goto yyrule6
	case 7:
		goto yyrule7
	case 8:
		goto yyrule8
	case 9:
		goto yyrule9
	case 10:
		goto yyrule10
	case 11:
		goto yyrule11
	case 12:
		goto yyrule12
	case 13:
		goto yyrule13
	case 14:
		goto yyrule14
	case 15:
		goto yyrule15
	case 16:
		goto yyrule16
	case 17:
		goto yyrule17
	case 18:
		goto yyrule18
	case 19:
		goto yyrule19
	case 20:
		goto yyrule20
	case 21:
		goto yyrule21
	case 22:
		goto yyrule22
	case 23:
		goto yyrule23
	}
	goto yystate1 // silence unused label error
yystate1:
	c = l.Next()
yystart1:
	switch {
	default:
		goto yyabort
	case c == '%':
		goto yystate6
	case c == '(':
		goto yystate8
	case c == ')':
		goto yystate10
	case c == '*':
		goto yystate11
	case c == '+':
		goto yystate13
	case c == ',':
		goto yystate15
	case c == '-':
		goto yystate17
	case c == '/':
		goto yystate19
	case c == ':':
		goto yystate22
	case c == ';':
		goto yystate23
	case c == '[':
		goto yystate25
	case c == '\n':
		goto yystate3
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	case c == ']':
		goto yystate27
	case c == 'b':
		goto yystate28
	case c == 'c':
		goto yystate32
	case c == 'd':
		goto yystate40
	case c == 'i':
		goto yystate44
	case c == '{':
		goto yystate47
	case c == '}':
		goto yystate49
	case c >= '0' && c <= '9':
		goto yystate21
	case c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c >= 'e' && c <= 'h' || c >= 'j' && c <= 'z' || c == '\u0080':
		goto yystate24
	}

yystate2:
	c = l.Next()
	yyrule = 1
	l.Mark()
	switch {
	default:
		goto yyrule1
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate2
	}

yystate3:
	c = l.Next()
	yyrule = 11
	l.Mark()
	switch {
	default:
		goto yyrule11
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate4
	}

yystate4:
	c = l.Next()
	switch {
	default:
		goto yyabort
	case c == ')':
		goto yystate5
	case c == '\t' || c == ' ':
		goto yystate4
	}

yystate5:
	c = l.Next()
	yyrule = 5
	l.Mark()
	goto yyrule5

yystate6:
	c = l.Next()
	yyrule = 17
	l.Mark()
	switch {
	default:
		goto yyrule17
	case c == '\n':
		goto yystate7
	case c == '\t' || c == ' ':
		goto yystate6
	}

yystate7:
	c = l.Next()
	yyrule = 17
	l.Mark()
	goto yyrule17

yystate8:
	c = l.Next()
	yyrule = 4
	l.Mark()
	switch {
	default:
		goto yyrule4
	case c == '\n':
		goto yystate9
	case c == '\t' || c == ' ':
		goto yystate8
	}

yystate9:
	c = l.Next()
	yyrule = 4
	l.Mark()
	goto yyrule4

yystate10:
	c = l.Next()
	yyrule = 6
	l.Mark()
	goto yyrule6

yystate11:
	c = l.Next()
	yyrule = 15
	l.Mark()
	switch {
	default:
		goto yyrule15
	case c == '\n':
		goto yystate12
	case c == '\t' || c == ' ':
		goto yystate11
	}

yystate12:
	c = l.Next()
	yyrule = 15
	l.Mark()
	goto yyrule15

yystate13:
	c = l.Next()
	yyrule = 13
	l.Mark()
	switch {
	default:
		goto yyrule13
	case c == '\n':
		goto yystate14
	case c == '\t' || c == ' ':
		goto yystate13
	}

yystate14:
	c = l.Next()
	yyrule = 13
	l.Mark()
	goto yyrule13

yystate15:
	c = l.Next()
	yyrule = 2
	l.Mark()
	switch {
	default:
		goto yyrule2
	case c == '\n':
		goto yystate16
	case c == '\t' || c == ' ':
		goto yystate15
	}

yystate16:
	c = l.Next()
	yyrule = 2
	l.Mark()
	goto yyrule2

yystate17:
	c = l.Next()
	yyrule = 14
	l.Mark()
	switch {
	default:
		goto yyrule14
	case c == '\n':
		goto yystate18
	case c == '\t' || c == ' ':
		goto yystate17
	}

yystate18:
	c = l.Next()
	yyrule = 14
	l.Mark()
	goto yyrule14

yystate19:
	c = l.Next()
	yyrule = 16
	l.Mark()
	switch {
	default:
		goto yyrule16
	case c == '\n':
		goto yystate20
	case c == '\t' || c == ' ':
		goto yystate19
	}

yystate20:
	c = l.Next()
	yyrule = 16
	l.Mark()
	goto yyrule16

yystate21:
	c = l.Next()
	yyrule = 22
	l.Mark()
	switch {
	default:
		goto yyrule22
	case c >= '0' && c <= '9':
		goto yystate21
	}

yystate22:
	c = l.Next()
	yyrule = 3
	l.Mark()
	goto yyrule3

yystate23:
	c = l.Next()
	yyrule = 12
	l.Mark()
	goto yyrule12

yystate24:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate25:
	c = l.Next()
	yyrule = 9
	l.Mark()
	switch {
	default:
		goto yyrule9
	case c == '\n':
		goto yystate26
	case c == '\t' || c == ' ':
		goto yystate25
	}

yystate26:
	c = l.Next()
	yyrule = 9
	l.Mark()
	goto yyrule9

yystate27:
	c = l.Next()
	yyrule = 10
	l.Mark()
	goto yyrule10

yystate28:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'o':
		goto yystate29
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate29:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'o':
		goto yystate30
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate30:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'l':
		goto yystate31
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate31:
	c = l.Next()
	yyrule = 20
	l.Mark()
	switch {
	default:
		goto yyrule20
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate32:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'o':
		goto yystate33
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate33:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'n':
		goto yystate34
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate34:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 't':
		goto yystate35
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate35:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'r':
		goto yystate36
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate36:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'a':
		goto yystate37
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate37:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'c':
		goto yystate38
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate38:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 't':
		goto yystate39
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate39:
	c = l.Next()
	yyrule = 19
	l.Mark()
	switch {
	default:
		goto yyrule19
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate40:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'a':
		goto yystate41
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate41:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 't':
		goto yystate42
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate42:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'a':
		goto yystate43
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate43:
	c = l.Next()
	yyrule = 18
	l.Mark()
	switch {
	default:
		goto yyrule18
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate44:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 'n':
		goto yystate45
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate45:
	c = l.Next()
	yyrule = 23
	l.Mark()
	switch {
	default:
		goto yyrule23
	case c == 't':
		goto yystate46
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate46:
	c = l.Next()
	yyrule = 21
	l.Mark()
	switch {
	default:
		goto yyrule21
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z' || c == '\u0080' || c == '\u0081':
		goto yystate24
	}

yystate47:
	c = l.Next()
	yyrule = 7
	l.Mark()
	switch {
	default:
		goto yyrule7
	case c == '\n':
		goto yystate48
	case c == '\t' || c == ' ':
		goto yystate47
	}

yystate48:
	c = l.Next()
	yyrule = 7
	l.Mark()
	goto yyrule7

yystate49:
	c = l.Next()
	yyrule = 8
	l.Mark()
	goto yyrule8

yyrule1: // [ \t\r ]+
	{
		// ignore all whitespace
		goto yystate0
	}
yyrule2: // ,[ \t]*\n?
	{
		return l.char(COMMA)
	}
yyrule3: // :
	{
		return l.char(COLON)
	}
yyrule4: // \([ \t]*\n?
	{
		return l.char(LPAREN)
	}
yyrule5: // \n[ \t]*\)
	{
		return l.char(RPAREN)
	}
yyrule6: // \)
	{
		return l.char(RPAREN)
	}
yyrule7: // \{[ \t]*\n?
	{
		return l.char(LBRACE)
	}
yyrule8: // \}
	{
		return l.char(RBRACE)
	}
yyrule9: // \[[ \t]*\n?
	{
		return l.char(LBRAKET)
	}
yyrule10: // \]
	{
		return l.char(RBRAKET)
	}
yyrule11: // \n
	{
		return l.char(NEWLINE)
	}
yyrule12: // ;
	{
		return l.char(NEWLINE)
	}
yyrule13: // \+[ \t]*\n?
	{
		return l.char(ADD)
	}
yyrule14: // -[ \t]*\n?
	{
		return l.char(SUB)
	}
yyrule15: // \*[ \t]*\n?
	{
		return l.char(MUL)
	}
yyrule16: // \/[ \t]*\n?
	{
		return l.char(DIV)
	}
yyrule17: // %[ \t]*\n?
	{
		return l.char(MOD)
	}
yyrule18: // data
	{
		return l.char(DATA)
	}
yyrule19: // contract
	{
		return l.char(CONTRACT)
	}
yyrule20: // bool
	{
		return l.char(T_BOOL)
	}
yyrule21: // int
	{
		return l.char(T_INT)
	}
yyrule22: // {int}
	{
		{
			lval.i, _ = strconv.Atoi(string(l.TokenBytes(nil)))
			return l.char(INT)
		}
		goto yystate0
	}
yyrule23: // {identifier}
	{
		{
			lval.s = string(l.TokenBytes(nil))
			return l.char(IDENT)
		}
		goto yystate0
	}
	panic("unreachable")

	goto yyabort // silence unused label error

yyabort: // no lexem recognized
	if c, ok := l.Abort(); ok {
		return l.char(c)
	}

	goto yyAction
}
